routes:
  /courses/:
    template: custom-courses
  /girls-who-code/:
    template: custom-girls-who-code
  # /cs-club/:
  #   template: custom-cs-club
  /robotics/:
    template: custom-robotics-club
  /weather/:
    template: custom-weather
  /ghc-gallery/:
    template: ghc-gallery
collections:
  /:
    permalink: /{slug}/
    template: index
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
