name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Gulp
        run: gulp

      - name: Upload Routes YAML
        run: |
          curl -X PUT "${{ secrets.GHOST_API_URL }}/settings/routes/yaml" \
          -H "Content-Type: application/json" \
          -H "Authorization: Ghost ${GHOST_ADMIN_API_KEY}" \
          --data-binary "@/content/themes/cgps-tech-website-ghost/routes.yaml"
        env:
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}

      - name: SSH and Restart Ghost
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ghost restart
            gulp
